version: "3.7"

services:
  letsencrypt-nginx:
    container_name: letsencrypt-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - $HOME/certbot/nginx.conf:/etc/nginx/conf.d/default.conf
      - $HOME/certbot/www:/usr/share/nginx/html

